jdbc:
  url: jdbc:mysql://localhost:3306/certdb
  username: root
  password: root
  driver-class-name: com.mysql.cj.jdbc.Driver

hibernate:
  dialect: org.hibernate.dialect.MySQL8Dialect

# logging properties
logging:
  # location of the log files
  file: logs/app.log
  configurations:
    all*.exclude group:'org.springframework.boot',
    module:'spring-boot-starter-logging'
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: INFO
    org.springframework.web: ERROR
    com.robert: DEBUG
    org.hibernate: ERROR
