spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:surveyTestDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      show_sql: true
      ddl-auto: create-drop
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      id.new_generator_mappings: true
  h2.console.enabled: true # the JDBC URL is jdbc:h2:mem:testdb

# logging properties
logging:
  # location of the log files
  file: logs/app.log
  configurations:
    all*.exclude group:'org.springframework.boot',
    module:'spring-boot-starter-logging'
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: INFO
    org.springframework.web: ERROR
    com.robert: DEBUG
    org.hibernate: ERROR
